# 🧪 3. API Gateway HTTP API (OpenAPI Template)
# Here’s a clean OpenAPI style routing template you can import into API Gateway.

openapi: 3.0.1
info:
  title: Yo-ai Agent Template
  version: 1.0.0

paths:

  /:
    get:
      x-amazon-apigateway-integration:
        type: http_proxy
        uri: https://<bucket>.s3.amazonaws.com/human/default-landing-page.html

  /human/talk:
    get:
      x-amazon-apigateway-integration:
        type: http_proxy
        uri: https://<bucket>.s3.amazonaws.com/human/talk.html

  /human/next-steps:
    get:
      x-amazon-apigateway-integration:
        type: http_proxy
        uri: https://<bucket>.s3.amazonaws.com/human/next-steps.html

  /.well-known/agent-card.json:
    get:
      x-amazon-apigateway-integration:
        type: http_proxy
        uri: https://<bucket>.s3.amazonaws.com/well-known/agent-card.json

  /.well-known/documentation.md:
    get:
      x-amazon-apigateway-integration:
        type: http_proxy
        uri: https://<bucket>.s3.amazonaws.com/well-known/documentation.md

  /api/card:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:<region>:<acct>:function:getCardHandler

  /api/register:
    post:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:<region>:<acct>:function:registerHandler

  /api/auth:
    post:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:<region>:<acct>:function:authHandler

  /api/permissions:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:<region>:<acct>:function:permissionsGetHandler
    post:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:<region>:<acct>:function:permissionsPostHandler

  /api/extended:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:<region>:<acct>:function:extendedHandler

  /api/talk:
    post:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:<region>:<acct>:function:talkHandler

  /api/health:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:lambda:<region>:<acct>:function:healthHandler

# This is the canonical importable template for all agents.
